# Day 4 Lab - Motif Finding: Part 1
The goal of today's lab is to write some code to find and score motifs.

#### (1) Write two functions,`Count` and `Profile`  ,have them take in a collection of DNA strings and have it return either the count or profile matrix.

Use numpy arrays to store your profile (or count) matrix.

`Count(["ATA", "ATT","GTT","TTT"])` would have an output of `np.array([[2,0,1], [0,0,0], [1,0,0],[1,4,3]])`<Br><br>
`Profile(["ATA", "ATT","GTT","TTT"])` would have an output of `array([[0.5 , 0.  , 0.25], [0.  , 0.  , 0.  ],[0.25, 0.  , 0.  ],[0.25, 1.  , 0.75]])`

In [8]:
import numpy as np
import math

In [9]:
def count(dna):
    l=len(dna[0])
    matrix = np.zeros((4,l))
    for i in range(l):
        dict = {'A':0, 'C':0, 'G':0, 'T':0}
        for seq in dna:
            dict[seq[i]]+=1
        j=0
        for key in dict:
            matrix[j,i]=dict[key]
            j+=1
    return matrix

def profile(dna):
    return count(dna)*(1/4)
x=["ATA","ATT","GTT","TTT"]
print(count(x))
print(profile(x))
            

[[2. 0. 1.]
 [0. 0. 0.]
 [1. 0. 0.]
 [1. 4. 3.]]
[[0.5  0.   0.25]
 [0.   0.   0.  ]
 [0.25 0.   0.  ]
 [0.25 1.   0.75]]


#### (2) Write a function that will calculate the entropy for each column of your profile.

A call of `Entropy(profile)` would yield a 1D array of entropy values.

In [ ]:
def entropy(profile):
    